### ISSUE TITLE
Trusted Tester implementation: act-r-rule-no-keyboard-trap-evaluation-report.json

### ISSUE THREAD

**Issue by kengdoj** [act-rules/act-rules-implementation-trusted-tester#1]
{
  "@graph": [
    {
      "@context": {
        "@vocab": "http://www.w3.org/TR/WCAG-EM/#",
        "reporter": "https://github.com/w3c/wcag-em-report-tool/",
        "wcagem": "http://www.w3.org/TR/WCAG-EM/#",
        "WCAG2": "http://www.w3.org/TR/WCAG20/#",
        "earl": "http://www.w3.org/ns/earl#",
        "dct": "http://purl.org/dc/terms/",
        "wai": "http://www.w3.org/WAI/",
        "sch": "http://schema.org/",
        "Evaluation": "wcagem:Evaluation",
        "EvaluationScope": "wcagem:EvaluationScope",
        "TestSubject": "earl:TestSubject",
        "WebSite": "sch:WebSite",
        "Sample": "wcagem:Sample",
        "WebPage": "sch:WebPage",
        "Technology": "WCAG2:technologydef",
        "Assertion": "earl:Assertion",
        "Assertor": "earl:Assertor",
        "TestResult": "earl:TestResult",
        "title": "dct:title",
        "summary": "dct:summary",
        "creator": {
          "@id": "dct:creator",
          "@type": "@id"
        },
        "date": "dct:date",
        "commissioner": "wcagem:commissioner",
        "reliedUponTechnology": "WCAG2:reliedupondef",
        "evaluationScope": "step1",
        "commonPages": "step2a",
        "essentialFunctionality": "step2b",
        "pageTypeVariety": "step2c",
        "otherRelevantPages": "step2e",
        "structuredSample": "step3a",
        "randomSample": "step3b",
        "auditResult": "step4",
        "specifics": "step5b",
        "publisher": {
          "@id": "dct:publisher",
          "@type": "@id"
        },
        "conformanceTarget": {
          "@id": "step1b",
          "@type": "@id"
        },
        "accessibilitySupportBaseline": "step1c",
        "additionalEvalRequirement": "step1d",
        "website": "WCAG2:set-of-web-pagesdef",
        "siteScope": "step1a",
        "siteName": "sch:name",
        "webpage": "WCAG2:webpagedef",
        "description": "dct:description",
        "source": {
          "@id": "dct:source",
          "@type": "@id"
        },
        "tested": "reporter:blob/master/docs/EARL%2BJSON-LD.md#tested",
        "test": {
          "@id": "earl:test",
          "@type": "@id"
        },
        "assertedBy": {
          "@id": "earl:assertedBy",
          "@type": "@id"
        },
        "subject": {
          "@id": "earl:subject",
          "@type": "@id"
        },
        "result": "earl:result",
        "mode": {
          "@id": "earl:mode",
          "@type": "@id"
        },
        "hasPart": "dct:hasPart",
        "outcome": {
          "@id": "earl:outcome",
          "@type": "@id"
        },
        "id": "@id",
        "type": "@type",
        "lang": "@language"
      },
      "type": "Evaluation",
      "publisher": "reporter:releases/tag/1.1.0",
      "lang": "en",
      "evaluationScope": {
        "type": "EvaluationScope",
        "conformanceTarget": "wai:WCAG2AA-Conformance",
        "additionalEvalRequirement": "",
        "website": {
          "type": [
            "TestSubject",
            "WebSite"
          ],
          "id": "_:website",
          "siteName": "ACT-R Rule - No keyboard trap",
          "siteScope": "https://act-rules.github.io/testcases/80af7b/"
        },
        "accessibilitySupportBaseline": "<< Fill out >>"
      },
      "auditResult": [
        {
          "type": "Assertion",
          "test": "WCAG2:text-equiv-all",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:media-equiv-av-only-alt",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:media-equiv-captions",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:media-equiv-audio-desc",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:media-equiv-real-time-captions",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:media-equiv-audio-desc-only",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:media-equiv-sign",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:media-equiv-extended-ad",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:media-equiv-text-doc",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:media-equiv-live-audio-only",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:content-structure-separation-programmatic",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:content-structure-separation-sequence",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:content-structure-separation-understanding",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:visual-audio-contrast-without-color",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:visual-audio-contrast-dis-audio",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:visual-audio-contrast-contrast",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:visual-audio-contrast-scale",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:visual-audio-contrast-text-presentation",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:visual-audio-contrast7",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:visual-audio-contrast-noaudio",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:visual-audio-contrast-visual-presentation",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:visual-audio-contrast-text-images",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:keyboard-operation-keyboard-operable",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:keyboard-operation-trapping",
          "assertedBy": "_:evaluator",
          "subject": "_:website",
          "result": {
            "date": "2019-06-14 12:12:45 -0400",
            "description": "results entered for testing in Chrome; IE11 results noted when different",
            "outcome": "earl:failed"
          },
          "mode": "earl:manual",
          "hasPart": [
            {
              "type": "Assertion",
              "assertedBy": "_:evaluator",
              "subject": [
                "_:struct_0"
              ],
              "result": {
                "date": "2019-06-13 20:32:45 -0400",
                "outcome": "earl:passed"
              },
              "multiPage": false,
              "mode": "earl:manual",
              "testcase": "WCAG2:keyboard-operation-trapping"
            },
            {
              "type": "Assertion",
              "assertedBy": "_:evaluator",
              "subject": [
                "_:struct_1"
              ],
              "result": {
                "date": "2019-06-14 11:39:24 -0400",
                "description": "",
                "outcome": "earl:passed"
              },
              "multiPage": false,
              "mode": "earl:manual",
              "testcase": "WCAG2:keyboard-operation-trapping"
            },
            {
              "type": "Assertion",
              "assertedBy": "_:evaluator",
              "subject": [
                "_:struct_2"
              ],
              "result": {
                "date": "2019-06-14 12:39:19 -0400",
                "description": "no keyboard focusable element",
                "outcome": "earl:inapplicable"
              },
              "multiPage": false,
              "mode": "earl:manual",
              "testcase": "WCAG2:keyboard-operation-trapping"
            },
            {
              "type": "Assertion",
              "assertedBy": "_:evaluator",
              "subject": [
                "_:struct_3"
              ],
              "result": {
                "date": "2019-06-14 11:59:30 -0400",
                "description": "M exit method works",
                "outcome": "earl:passed"
              },
              "multiPage": false,
              "mode": "earl:manual",
              "testcase": "WCAG2:keyboard-operation-trapping"
            },
            {
              "type": "Assertion",
              "assertedBy": "_:evaluator",
              "subject": [
                "_:struct_4"
              ],
              "result": {
                "date": "2019-06-14 11:59:33 -0400",
                "description": "M exit method works",
                "outcome": "earl:passed"
              },
              "multiPage": false,
              "mode": "earl:manual",
              "testcase": "WCAG2:keyboard-operation-trapping"
            },
            {
              "type": "Assertion",
              "assertedBy": "_:evaluator",
              "subject": [
                "_:struct_5"
              ],
              "result": {
                "date": "2019-06-14 12:46:11 -0400",
                "description": "Help instruction provided exit method that works",
                "outcome": "earl:passed"
              },
              "multiPage": false,
              "mode": "earl:manual",
              "testcase": "WCAG2:keyboard-operation-trapping"
            },
            {
              "type": "Assertion",
              "assertedBy": "_:evaluator",
              "subject": [
                "_:struct_6"
              ],
              "result": {
                "date": "2019-06-13 20:52:26 -0400",
                "outcome": "earl:passed"
              },
              "multiPage": false,
              "mode": "earl:manual",
              "testcase": "WCAG2:keyboard-operation-trapping"
            },
            {
              "type": "Assertion",
              "assertedBy": "_:evaluator",
              "subject": [
                "_:struct_7"
              ],
              "result": {
                "date": "2019-06-13 20:53:10 -0400",
                "outcome": "earl:passed"
              },
              "multiPage": false,
              "mode": "earl:manual",
              "testcase": "WCAG2:keyboard-operation-trapping"
            },
            {
              "type": "Assertion",
              "assertedBy": "_:evaluator",
              "subject": [
                "_:struct_8"
              ],
              "result": {
                "date": "2019-06-14 12:13:48 -0400",
                "description": "trap on Button 1 in Chrome; passes in IE11",
                "outcome": "earl:failed"
              },
              "multiPage": false,
              "mode": "earl:manual",
              "testcase": "WCAG2:keyboard-operation-trapping"
            },
            {
              "type": "Assertion",
              "assertedBy": "_:evaluator",
              "subject": [
                "_:struct_9"
              ],
              "result": {
                "date": "2019-06-14 12:16:14 -0400",
                "description": "trap on button 1 and button 2 loop",
                "outcome": "earl:failed"
              },
              "multiPage": false,
              "mode": "earl:manual",
              "testcase": "WCAG2:keyboard-operation-trapping"
            },
            {
              "type": "Assertion",
              "assertedBy": "_:evaluator",
              "subject": [
                "_:struct_10"
              ],
              "result": {
                "date": "2019-06-14 12:17:51 -0400",
                "description": "trap on button 1 and button 2 loop",
                "outcome": "earl:failed"
              },
              "multiPage": false,
              "mode": "earl:manual",
              "testcase": "WCAG2:keyboard-operation-trapping"
            },
            {
              "type": "Assertion",
              "assertedBy": "_:evaluator",
              "subject": [
                "_:struct_11"
              ],
              "result": {
                "date": "2019-06-14 12:19:13 -0400",
                "description": "trap on button 1 and button 2 loop, M-key did not exit trap",
                "outcome": "earl:failed"
              },
              "multiPage": false,
              "mode": "earl:manual",
              "testcase": "WCAG2:keyboard-operation-trapping"
            },
            {
              "type": "Assertion",
              "assertedBy": "_:evaluator",
              "subject": [
                "_:struct_12"
              ],
              "result": {
                "date": "2019-06-14 12:34:45 -0400",
                "description": "no keyboard focusable element",
                "outcome": "earl:inapplicable"
              },
              "multiPage": false,
              "mode": "earl:manual",
              "testcase": "WCAG2:keyboard-operation-trapping"
            },
            {
              "type": "Assertion",
              "assertedBy": "_:evaluator",
              "subject": [
                "_:struct_13"
              ],
              "result": {
                "date": "2019-06-14 12:34:33 -0400",
                "description": "no keyboard focusable element",
                "outcome": "earl:inapplicable"
              },
              "multiPage": false,
              "mode": "earl:manual",
              "testcase": "WCAG2:keyboard-operation-trapping"
            },
            {
              "type": "Assertion",
              "assertedBy": "_:evaluator",
              "subject": [
                "_:struct_14"
              ],
              "result": {
                "date": "2019-06-14 12:36:11 -0400",
                "description": "no keyboard focusable element",
                "outcome": "earl:inapplicable"
              },
              "multiPage": false,
              "mode": "earl:manual",
              "testcase": "WCAG2:keyboard-operation-trapping"
            },
            {
              "type": "Assertion",
              "assertedBy": "_:evaluator",
              "subject": [
                "_:struct_15"
              ],
              "result": {
                "date": "2019-06-14 12:46:35 -0400",
                "description": "no keyboard focusable element",
                "outcome": "earl:inapplicable"
              },
              "multiPage": false,
              "mode": "earl:manual",
              "testcase": "WCAG2:keyboard-operation-trapping"
            }
          ]
        },
        {
          "type": "Assertion",
          "test": "WCAG2:keyboard-operation-all-funcs",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:time-limits-required-behaviors",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:time-limits-pause",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:time-limits-no-exceptions",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:time-limits-postponed",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:time-limits-server-timeout",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:seizure-does-not-violate",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:seizure-three-times",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:navigation-mechanisms-skip",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:navigation-mechanisms-title",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:navigation-mechanisms-focus-order",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:navigation-mechanisms-refs",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:navigation-mechanisms-mult-loc",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:navigation-mechanisms-descriptive",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:navigation-mechanisms-focus-visible",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:navigation-mechanisms-location",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:navigation-mechanisms-link",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:navigation-mechanisms-headings",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:meaning-doc-lang-id",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:meaning-other-lang-id",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:meaning-idioms",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:meaning-located",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:meaning-supplements",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:meaning-pronunciation",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:consistent-behavior-receive-focus",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:consistent-behavior-unpredictable-change",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:consistent-behavior-consistent-locations",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:consistent-behavior-consistent-functionality",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:consistent-behavior-no-extreme-changes-context",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:minimize-error-identified",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:minimize-error-cues",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:minimize-error-suggestions",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:minimize-error-reversible",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:minimize-error-context-help",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:minimize-error-reversible-all",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:ensure-compat-parses",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        },
        {
          "type": "Assertion",
          "test": "WCAG2:ensure-compat-rsv",
          "subject": "_:website",
          "result": {
            "description": "",
            "outcome": "earl:untested"
          },
          "hasPart": []
        }
      ],
      "creator": "_:evaluator",
      "title": "Report for ACT-R Rule - No keyboard trap",
      "commissioner": "ACT Rules Community Group",
      "date": "June 17, 2019",
      "summary": "\"Not present\" result was found for a \"Passed\" example. An issue will be logged for Trusted Tester to review and address this in a future update.",
      "structuredSample": {
        "webpage": [
          {
            "type": [
              "TestSubject",
              "WebPage"
            ],
            "id": "_:struct_0",
            "description": "https://act-rules.github.io/testcases/80af7b/69410ed3505eb1562185b9f862ba37d927998de8.html",
            "source": "https://act-rules.github.io/testcases/80af7b/69410ed3505eb1562185b9f862ba37d927998de8.html",
            "title": "69410ed3505eb1562185b9f862ba37d927998de8",
            "tested": false
          },
          {
            "type": [
              "TestSubject",
              "WebPage"
            ],
            "id": "_:struct_1",
            "description": "https://act-rules.github.io/testcases/80af7b/cb7788489955008fa42baa4f29929ec9d0c229fc.html",
            "source": "https://act-rules.github.io/testcases/80af7b/cb7788489955008fa42baa4f29929ec9d0c229fc.html",
            "title": "cb7788489955008fa42baa4f29929ec9d0c229fc",
            "tested": false
          },
          {
            "type": [
              "TestSubject",
              "WebPage"
            ],
            "id": "_:struct_2",
            "description": "https://act-rules.github.io/testcases/80af7b/bb305c5ab78c9404613f3ad60b42aa1f2c5cdb57.html",
            "source": "https://act-rules.github.io/testcases/80af7b/bb305c5ab78c9404613f3ad60b42aa1f2c5cdb57.html",
            "title": "bb305c5ab78c9404613f3ad60b42aa1f2c5cdb57",
            "tested": false
          },
          {
            "type": [
              "TestSubject",
              "WebPage"
            ],
            "id": "_:struct_3",
            "description": "https://act-rules.github.io/testcases/80af7b/3736456f46e6ba4994fe5888d8c3ef75fbf6821f.html",
            "source": "https://act-rules.github.io/testcases/80af7b/3736456f46e6ba4994fe5888d8c3ef75fbf6821f.html",
            "title": "3736456f46e6ba4994fe5888d8c3ef75fbf6821f",
            "tested": false
          },
          {
            "type": [
              "TestSubject",
              "WebPage"
            ],
            "id": "_:struct_4",
            "description": "https://act-rules.github.io/testcases/80af7b/49eb23fe84cdb0800aea8fe2c3e967a21e3f8e3c.html",
            "source": "https://act-rules.github.io/testcases/80af7b/49eb23fe84cdb0800aea8fe2c3e967a21e3f8e3c.html",
            "title": "49eb23fe84cdb0800aea8fe2c3e967a21e3f8e3c",
            "tested": false
          },
          {
            "type": [
              "TestSubject",
              "WebPage"
            ],
            "id": "_:struct_5",
            "description": "https://act-rules.github.io/testcases/80af7b/fa6c08882f371b132c7619bec16c3d6ea3ccc054.html",
            "source": "https://act-rules.github.io/testcases/80af7b/fa6c08882f371b132c7619bec16c3d6ea3ccc054.html",
            "title": "fa6c08882f371b132c7619bec16c3d6ea3ccc054",
            "tested": false
          },
          {
            "type": [
              "TestSubject",
              "WebPage"
            ],
            "id": "_:struct_6",
            "description": "https://act-rules.github.io/testcases/80af7b/3820e644ceea98676c75189b1f3dfbb7854ec1b4.html",
            "source": "https://act-rules.github.io/testcases/80af7b/3820e644ceea98676c75189b1f3dfbb7854ec1b4.html",
            "title": "3820e644ceea98676c75189b1f3dfbb7854ec1b4",
            "tested": false
          },
          {
            "type": [
              "TestSubject",
              "WebPage"
            ],
            "id": "_:struct_7",
            "description": "https://act-rules.github.io/testcases/80af7b/260116f282e6b2306a085c21122974d1c6712d05.html",
            "source": "https://act-rules.github.io/testcases/80af7b/260116f282e6b2306a085c21122974d1c6712d05.html",
            "title": "260116f282e6b2306a085c21122974d1c6712d05",
            "tested": false
          },
          {
            "type": [
              "TestSubject",
              "WebPage"
            ],
            "id": "_:struct_8",
            "description": "https://act-rules.github.io/testcases/80af7b/78fa1137d4ca4e566718258caf700b99f52fb503.html",
            "source": "https://act-rules.github.io/testcases/80af7b/78fa1137d4ca4e566718258caf700b99f52fb503.html",
            "title": "78fa1137d4ca4e566718258caf700b99f52fb503",
            "tested": false
          },
          {
            "type": [
              "TestSubject",
              "WebPage"
            ],
            "id": "_:struct_9",
            "description": "https://act-rules.github.io/testcases/80af7b/d088ee2ba8ac1013dbf96976181e43128e2566ed.html",
            "source": "https://act-rules.github.io/testcases/80af7b/d088ee2ba8ac1013dbf96976181e43128e2566ed.html",
            "title": "d088ee2ba8ac1013dbf96976181e43128e2566ed",
            "tested": false
          },
          {
            "type": [
              "TestSubject",
              "WebPage"
            ],
            "id": "_:struct_10",
            "description": "https://act-rules.github.io/testcases/80af7b/cce1815dbe99e85431c7414751e75c943a04a1c7.html",
            "source": "https://act-rules.github.io/testcases/80af7b/cce1815dbe99e85431c7414751e75c943a04a1c7.html",
            "title": "cce1815dbe99e85431c7414751e75c943a04a1c7",
            "tested": false
          },
          {
            "type": [
              "TestSubject",
              "WebPage"
            ],
            "id": "_:struct_11",
            "description": "https://act-rules.github.io/testcases/80af7b/ed4e193b55daa159fb9278340a8de6bfc9fdd8c3.html",
            "source": "https://act-rules.github.io/testcases/80af7b/ed4e193b55daa159fb9278340a8de6bfc9fdd8c3.html",
            "title": "ed4e193b55daa159fb9278340a8de6bfc9fdd8c3",
            "tested": false
          },
          {
            "type": [
              "TestSubject",
              "WebPage"
            ],
            "id": "_:struct_12",
            "description": "https://act-rules.github.io/testcases/80af7b/0b85651f7b5522930967a5e243706419b81324ae.html",
            "source": "https://act-rules.github.io/testcases/80af7b/0b85651f7b5522930967a5e243706419b81324ae.html",
            "title": "0b85651f7b5522930967a5e243706419b81324ae",
            "tested": false
          },
          {
            "type": [
              "TestSubject",
              "WebPage"
            ],
            "id": "_:struct_13",
            "description": "https://act-rules.github.io/testcases/80af7b/117c07dd49f45f6180e42f261bb706b3c7345a19.html",
            "source": "https://act-rules.github.io/testcases/80af7b/117c07dd49f45f6180e42f261bb706b3c7345a19.html",
            "title": "117c07dd49f45f6180e42f261bb706b3c7345a19",
            "tested": false
          },
          {
            "type": [
              "TestSubject",
              "WebPage"
            ],
            "id": "_:struct_14",
            "description": "https://act-rules.github.io/testcases/80af7b/ef698dcb80787790ad086be6abdc79493f02c5ab.html",
            "source": "https://act-rules.github.io/testcases/80af7b/ef698dcb80787790ad086be6abdc79493f02c5ab.html",
            "title": "ef698dcb80787790ad086be6abdc79493f02c5ab",
            "tested": false
          },
          {
            "type": [
              "TestSubject",
              "WebPage"
            ],
            "id": "_:struct_15",
            "description": "https://act-rules.github.io/testcases/80af7b/0c9c757ddef9ea73ab3d3950668729a80aa03331.html",
            "source": "https://act-rules.github.io/testcases/80af7b/0c9c757ddef9ea73ab3d3950668729a80aa03331.html",
            "title": "0c9c757ddef9ea73ab3d3950668729a80aa03331",
            "tested": false
          }
        ]
      },
      "randomSample": {
        "webpage": []
      },
      "reliedUponTechnology": [
        {
          "id": "http://www.w3.org/TR/html5/",
          "type": "Technology",
          "title": "HTML5"
        }
      ]
    },
    {
      "@context": {
        "@vocab": "http://xmlns.com/foaf/0.1/",
        "id": "@id",
        "type": "@type"
      },
      "id": "_:evaluator",
      "type": "Person",
      "name": "Kathy Eng for Trusted Tester version 5"
    }
  ]
}

**Comment by jeeyyy** [comment]
Closing this issue as report has been added to the repository - https://github.com/act-rules/act-rules-implementation-access-board/tree/master/reports
