### ISSUE TITLE
Trusted Tester Implementation Report for Image button has accessible name

### ISSUE THREAD

**Issue by kengdoj** [act-rules/act-rules-implementation-trusted-tester#4]
For [Image button has accessible name](https://act-rules.github.io/rules/59796f)

[act-r-rule-image-button-has-accessible-name-TTevaluation-report.zip](https://github.com/act-rules/act-rules.github.io/files/3897639/act-r-rule-image-button-has-accessible-name-TTevaluation-report.zip)

**Comment by jeeyyy** [comment]
@kengdoj as discussed this is out of date, so closing the issue.

Please submit updated implementation.
